name: Lint file when push

on:
  push:
    branches: [main]

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show api file
        run: cat server/zally-test/src/main/resources/fixtures/api_spa.yaml
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-file
          path: server/zally-test/src/main/resources/fixtures/api_spa.yaml
      - name:
        run: echo ${{ steps.upload.outputs.artifact_id }}
