name: Lint file when push

on:
  push:
    branches: [main]

jobs:
  lint-api:
    uses: cekinmezyucel/zally/.github/workflows/validation-check-with-cli.yml@main
    with:
      file: 'server/zally-test/src/main/resources/fixtures/api_spa.yaml'
    secrets: inherit