name: Zally api specification linter

on:
  workflow_call:
    inputs:
      artifact-id:
        description: 'The artifact-id to the uploaded api specification file to be passed as input.'
        required: false
        type: string
      file-path:
        required: false
        type: string

jobs:
  build-zally:
    runs-on: ubuntu-latest
    steps:
      - name: Try to cat
        run: cat ${{ inputs.file-path }}
      - name: Checkout Zally
        uses: actions/checkout@v3
        with:
          repository: cekinmezyucel/zally
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: zally
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Add Zally CLI Path
        run: echo "/home/runner/work/zally/zally/cli/zally" >> $GITHUB_PATH
      - name: Run Zally server
        run: |
          cd /zally/server/
          ls
          pwd
          chmod +x gradlew
          ./gradlew --console=plain bootRun > /dev/null &
          echo $! > /tmp/zally_server.pid
          cd ..
          while ! echo "GET / HTTP/1.0\n" | nc localhost 8000; do sleep 1; done
      - name: Build CLI
        run: |
          cd zally/cli/zally
          go build
      - name: Lint file
        run: zally lint ${{ inputs.file-path }}